# Generated by Django 5.0.2 on 2024-02-08 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30, null=True)),
                ('task_description', models.TextField()),
                ('task_priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=30, null=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_status', models.BooleanField(default=False)),
            ],
        ),
    ]
