# Generated by Django 5.0.2 on 2024-02-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_add_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='task_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
