# Generated by Django 5.0.2 on 2024-02-08 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_add_task_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_task',
            name='task_categorie',
            field=models.CharField(choices=[('eat', 'eat'), ('play', 'play'), ('sleep', 'sleep')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='add_task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
