# Generated by Django 5.0.2 on 2024-02-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_add_task_task_categorie_add_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.user_profile'),
        ),
    ]
